import Foundation
import Security
import CryptoKit
import SystemConfiguration

struct LocalTLSIdentity {
    let identity: SecIdentity
    let fingerprint: String
    static let port: UInt16 = 8766
    // Keep the existing identity directory: changing it invalidates every Watch certificate pin.
    static var directory: URL {
        FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("WatchWhisper/tls", isDirectory: true)
    }
    static func prepare() throws -> LocalTLSIdentity {
        let directory = directory, fm = FileManager.default
        try fm.createDirectory(at: directory, withIntermediateDirectories: true, attributes: [.posixPermissions: 0o700])
        try fm.setAttributes([.posixPermissions: 0o700], ofItemAtPath: directory.path)
        let archive = directory.appendingPathComponent("identity-rsa.p12")
        let passwordFile = directory.appendingPathComponent("identity.password")
        let key = directory.appendingPathComponent("key-rsa.pem")
        let certificateFile = directory.appendingPathComponent("certificate-rsa.pem")
        let needsArchive = !fm.fileExists(atPath: archive.path)
        let needsPassword = !fm.fileExists(atPath: passwordFile.path)
        if needsArchive {
            try run(["req", "-x509", "-newkey", "rsa:2048",
                     "-sha256", "-days", "365", "-nodes", "-subj", "/CN=Micodex Local",
                     "-keyout", key.path, "-out", certificateFile.path])
        } else if needsPassword {
            // Upgrade only an identity generated by an interrupted initial setup.
            try run(["pkcs12", "-in", archive.path, "-passin", "pass:", "-nodes", "-nocerts", "-out", key.path])
        }
        if needsPassword {
            var random = [UInt8](repeating: 0, count: 32)
            guard SecRandomCopyBytes(kSecRandomDefault, random.count, &random) == errSecSuccess else { throw Failure("无法生成本机身份保护密码。") }
            try Data(random.map { String(format: "%02x", $0) }.joined().utf8).write(to: passwordFile, options: .atomic)
            try fm.setAttributes([.posixPermissions: 0o600], ofItemAtPath: passwordFile.path)
        }
        if needsArchive || needsPassword {
            try fm.setAttributes([.posixPermissions: 0o600], ofItemAtPath: key.path)
            let temporary = directory.appendingPathComponent("identity-new.p12")
            try run(["pkcs12", "-export", "-inkey", key.path, "-in", certificateFile.path,
                     "-out", temporary.path, "-passout", "file:" + passwordFile.path])
            try fm.setAttributes([.posixPermissions: 0o600], ofItemAtPath: temporary.path)
            if needsArchive { try fm.moveItem(at: temporary, to: archive) }
            else { _ = try fm.replaceItemAt(archive, withItemAt: temporary) }
            try fm.removeItem(at: key)
        }
        guard #available(macOS 15.0, *) else { throw Failure("Wi-Fi 直连需要 macOS 15 或更新版本。") }
        let password = try String(contentsOf: passwordFile, encoding: .utf8)
        var items: CFArray?
        let result = SecPKCS12Import(try Data(contentsOf: archive) as CFData,
                                    [kSecImportExportPassphrase as String: password, kSecImportToMemoryOnly as String: true] as CFDictionary, &items)
        guard result == errSecSuccess, let first = (items as? [[String: Any]])?.first,
              let value = first[kSecImportItemIdentity as String] else { throw Failure("无法读取本机 TLS 身份（\(result)）。") }
        let identity = value as! SecIdentity
        var certificate: SecCertificate?
        guard SecIdentityCopyCertificate(identity, &certificate) == errSecSuccess, let certificate else {
            throw Failure("本机 TLS 证书不可用。")
        }
        let der = SecCertificateCopyData(certificate) as Data
        try der.write(to: directory.appendingPathComponent("certificate.der"), options: .atomic)
        return LocalTLSIdentity(identity: identity, fingerprint: SHA256.hash(data: der).map { String(format: "%02x", $0) }.joined())
    }
    static func localAddress() -> String? {
        guard let store = SCDynamicStoreCreate(nil, "Micodex" as CFString, nil, nil),
              let global = SCDynamicStoreCopyValue(store, "State:/Network/Global/IPv4" as CFString) as? [String: Any] else { return nil }
        // A VPN may be the primary service; choose a real local interface.
        let primary = global["PrimaryInterface"] as? String ?? "en0"
        let candidates = Array(Set(["en0", primary] + (0...10).map { "en\($0)" })).sorted { a,b in
            if a == "en0" { return b != "en0" }; if b == "en0" { return false }; return a < b
        }
        for name in candidates where name.hasPrefix("en") {
            guard let value = SCDynamicStoreCopyValue(store, "State:/Network/Interface/\(name)/IPv4" as CFString) as? [String: Any],
                  let addresses = value["Addresses"] as? [String],
                  let address = addresses.first(where: { $0.hasPrefix("192.168.") || $0.hasPrefix("10.") || (16...31).contains(Int($0.split(separator: ".").dropFirst().first ?? "") ?? 0) && $0.hasPrefix("172.") }) else { continue }
            return address
        }
        return nil
    }
    private static func run(_ arguments: [String]) throws {
        let process = Process(), errors = Pipe()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/openssl"); process.arguments = arguments
        process.standardOutput = FileHandle.nullDevice; process.standardError = errors
        try process.run()
        let data = errors.fileHandleForReading.readDataToEndOfFile(); process.waitUntilExit()
        guard process.terminationStatus == 0 else {
            throw Failure("本机证书准备失败：\(String(decoding: data, as: UTF8.self).prefix(180))")
        }
    }
    struct Failure: LocalizedError {
        let message: String
        init(_ message: String) { self.message = message }
        var errorDescription: String? { message }
    }
}
