#!/usr/bin/env python3
"""Generate native English/Chinese resources from reviewable source catalogs."""
import argparse
import json
from pathlib import Path
import re

root = Path(__file__).resolve().parent.parent
parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
merged = {}
for path in sorted((root / 'Localization').glob('*.json')):
    for key, translation in json.loads(path.read_text()).items():
        assert isinstance(key, str) and isinstance(translation, str)
        assert not re.search(r'[\u3400-\u9fff]', key), f'Non-English source key: {key}'
        # Only string substitution is used; punctuation and data are never formats.
        def tokens(text):
            return re.findall(r'%(?:\d+\$)?[@dfilsuxX]', text.replace('%%', ''))
        assert tokens(key) == tokens(translation), f'Format mismatch in {path.name}: {key}'
        if key in merged:
            assert merged[key] == translation, f'Conflicting translations for {key}'
        merged[key] = translation
for language in ['en', 'zh-Hans']:
    content = '/* Generated by scripts/generate-localizations.py. Edit Localization/*.json. */\n'
    content += '\n'.join(json.dumps(key, ensure_ascii=False) + ' = ' +
                         json.dumps(key if language == 'en' else value, ensure_ascii=False) + ';'
                         for key, value in sorted(merged.items())) + '\n'
    output = root / 'Sources/MicodexCore/Resources' / f'{language}.lproj/Localizable.strings'
    if args.check:
        assert output.read_text() == content, f'Outdated catalog: {output}'
    else:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(content)

# Audit source calls and resources together so untranslated runtime messages cannot
# silently fall back to an English-only key on Chinese devices.
keys = set()
for directory in ['Mac', 'Watch', 'Shared', 'Sources/MicodexCore']:
    for path in (root / directory).rglob('*.swift'):
        for match in re.finditer(r'L10n\.(?:t|message)\("((?:[^"\\]|\\.)*)"', path.read_text()):
            key = json.loads('"' + match[1] + '"')
            keys.add(key)
            assert key in merged, f'Missing translation in {path.relative_to(root)}: {key}'
print(f'Validated {len(merged)} English/Chinese translations and {len(keys)} source keys')
